-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE example_note (
  exnote_id SERIAL NOT NULL,
  exnote_user INT NOT NULL,
  exnote_page INT NOT NULL,
  exnote_value TEXT DEFAULT NULL,
  PRIMARY KEY(exnote_id)
);

CREATE INDEX exnote_user_page ON example_note (exnote_user, exnote_page);

CREATE INDEX exnote_page_user ON example_note (exnote_page, exnote_user);
