-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/example_note (
  exnote_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  exnote_user INT UNSIGNED NOT NULL,
  exnote_page INT UNSIGNED NOT NULL,
  exnote_value LONGBLOB DEFAULT NULL,
  INDEX exnote_user_page (exnote_user, exnote_page),
  INDEX exnote_page_user (exnote_page, exnote_user),
  PRIMARY KEY(exnote_id)
) /*$wgDBTableOptions*/;
